apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: bridb-httpd
    name: bridb-httpd
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/openshift/bridb-httpd:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
kind: List
metadata: {}
